#!/bin/bash

# kill previously running versions of the script
# only works if the versions of the script were run with the same script_name
script_name=${BASH_SOURCE[0]}
for pid in $(pidof -x $script_name); do
    if [ $pid != $$ ]; then
        kill -9 $pid
    fi
done

# 02:00 Change to 2
# 04:00 Change to 3
# 06:00 Change to 4
# 08:00 Change to 5
# 10:00 Change to 6
# 12:00 Change to 7
# 14:00 Change to 8
# 16:00 Change to 9
# 18:00 Change to 10
# 20:00 Change to 11
# 22:00 Change to 12
# 24:00 Change to 1 (Actually 23:59)


function update_times {
    for i in {0..10}
    do
        time_until[$i]=$(( $(date -d $(((${i}+1) * 2))00 +%s) - $(date +%s) ))
    done
    time_until[11]=$(( $(date -d 2359 +%s) - $(date +%s) ))
    echo Times: ${time_until[@]}
}

update_times

# Rotate to what should be the current wallpaper
#update_times
echo Setting starting wallpaper to 1
if [ ${time_until[11]} -lt 0 ]
then
    echo Edge case: time is between 23:59 and 00:00. Treating as 00:00 next day. Not transitioning.
else
    for i in {0..11}
    do
        if [ ${time_until[$i]} -lt 0 ]
        then
            echo Transitioning from $(($i+1)) to $(($i+2))
            ~/.wallpaper/transition ~/.wallpaper/wallpaper$(($i+1)).jpeg ~/.wallpaper/wallpaper$(($i+2)).jpeg ~/.wallpaper/transitions
        else
            break
        fi
    done
fi

while :
do
    update_times
    for i in {0..11}
    do
        if [ ${time_until[$i]} -gt 0 ]
        then
            if [ $i -eq 11 ]
            then
                echo Transitioning from $(($i+1)) to 1 in ${time_until[$i]}
                sleep ${time_until[$i]}
                echo Transitioning from $(($i+1)) to 1
                ~/.wallpaper/transition ~/.wallpaper/wallpaper$(($i+1)).jpeg ~/.wallpaper/wallpaper1.jpeg ~/.wallpaper/transitions
                sleep 60
            else
                echo Transitioning from $(($i+1)) to $(($i+2)) in ${time_until[$i]}
                sleep ${time_until[$i]}
                echo Transitioning from $(($i+1)) to $(($i+2)) 
                ~/.wallpaper/transition ~/.wallpaper/wallpaper$(($i+1)).jpeg ~/.wallpaper/wallpaper$(($i+2)).jpeg ~/.wallpaper/transitions
            fi
            break
        fi
    done
done
