#!/bin/bash

# kill previously running versions of the script
# only works if the versions of the script were run with the same script_name
script_name=${BASH_SOURCE[0]}
for pid in $(pidof -x $script_name); do
    if [ $pid != $$ ]; then
        kill -9 $pid
    fi
done

# What each array index means:
# [00] time until 02:00. Then, change to 2
# [01] time until 04:00. Then, change to 3
# [02] time until 06:00. Then, change to 4
# [03] time until 08:00. Then, change to 5
# [04] time until 10:00. Then, change to 6
# [05] time until 12:00. Then, change to 7
# [06] time until 14:00. Then, change to 8
# [07] time until 16:00. Then, change to 9
# [08] time until 18:00. Then, change to 10
# [09] time until 20:00. Then, change to 11
# [10] time until 22:00. Then, change to 12
# [11] time until 24:00. Then, change to 1 (Actually 23:59)

function update_times {
    for i in {0..10}
    do
        time_until[$i]=$(( $(date -d $(((${i}+1) * 2))00 +%s) - $(date +%s) ))
    done
    time_until[11]=$(( $(date -d 2359 +%s) - $(date +%s) ))
    echo Times: ${time_until[@]}
}

update_times

# Rotate to what should be the current wallpaper
#update_times
echo Setting starting wallpaper to 1
if [ ${time_until[11]} -lt 0 ]
then
    echo Edge case: time is between 23:59 and 00:00. Treating as 00:00 next day. Not transitioning.
else
    for i in {0..11}
    do
        if [ ${time_until[$i]} -lt 0 ]
        then
            echo Transitioning from $(($i+1)) to $(($i+2))
            ~/.wallpaper/transition ~/.wallpaper/wallpaper$(($i+1)).jpeg ~/.wallpaper/wallpaper$(($i+2)).jpeg ~/.wallpaper/transitions
        else
            break
        fi
    done
fi

while :
do
    update_times
    for i in {0..11}
    do
        if [ ${time_until[$i]} -gt 0 ]
        then
            if [ $i -eq 11 ]
            then
                echo Transitioning from $(($i+1)) to 1 in ${time_until[$i]}
                sleep ${time_until[$i]}
                echo Transitioning from $(($i+1)) to 1
                ~/.wallpaper/transition ~/.wallpaper/wallpaper$(($i+1)).jpeg ~/.wallpaper/wallpaper1.jpeg ~/.wallpaper/transitions
                sleep 60
            else
                echo Transitioning from $(($i+1)) to $(($i+2)) in ${time_until[$i]}
                sleep ${time_until[$i]}
                echo Transitioning from $(($i+1)) to $(($i+2)) 
                ~/.wallpaper/transition ~/.wallpaper/wallpaper$(($i+1)).jpeg ~/.wallpaper/wallpaper$(($i+2)).jpeg ~/.wallpaper/transitions
            fi
            break
        fi
    done
done
